#!/usr/bin/env bash

config_tnsnames_ora()
{

if [ ! -f "${ORACLE_HOME}/network/admin/tnsnames.ora" ];then

{

cat << EOF > ${ORACLE_HOME}/network/admin/tnsnames.ora
${DATABASE_NAME} =
  (DESCRIPTION =
    (ADDRESS = (PROTOCOL = TCP)(HOST = ${HOSTNAME})(PORT = 1521))
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SERVICE_NAME = ${DB_INSTANCE})
    )
  )
EOF

chown oracle:dba -v ${ORACLE_HOME}/network/admin/tnsnames.ora 1>> "${LOG_OUT}" 2>> "${LOG_ERROR}"
chmod +x -v ${ORACLE_HOME}/network/admin/tnsnames.ora 1>> "${LOG_OUT}" 2>> "${LOG_ERROR}"

} &> /dev/null && echo -e "${GREEN}TNSNAMES ..............................OK!${NC}\n"

else
    echo -e "${GREEN}TNSNAMES ..............................OK!${NC}\n"
fi
}